# Generated by Django 4.0.1 on 2022-03-27 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RcptGenerator', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rec',
            new_name='Receipt',
        ),
    ]
