# Generated by Django 4.0.1 on 2022-03-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RcptGenerator', '0002_rename_rec_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='date',
            field=models.DateField(),
        ),
    ]
