# Generated by Django 4.0.1 on 2022-03-27 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RcptGenerator', '0003_alter_receipt_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='username',
            new_name='username_Receipt',
        ),
    ]
