# Generated by Django 4.0.1 on 2022-03-27 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RcptGenerator', '0004_rename_username_receipt_username_receipt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receipt',
            old_name='username_Receipt',
            new_name='username',
        ),
    ]
