# Generated by Django 4.0.1 on 2022-04-13 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RcptGenerator', '0007_product_display_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
