# Generated by Django 4.0.1 on 2022-05-15 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RcptGenerator', '0009_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
