# Generated by Django 4.0.1 on 2022-05-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RcptGenerator', '0010_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
