# Generated by Django 4.0.1 on 2022-05-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RcptGenerator', '0013_product_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=1023)),
                ('message', models.CharField(max_length=5000)),
                ('date', models.DateField()),
            ],
        ),
    ]
